name = "nazieraaziz-cms"
compatibility_date = "2026-07-24"
pages_build_output_dir = "."

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "naziera-cms"
database_id = "d5858cec-5b7e-4e0c-8361-9136b607d027"